
import Anthropic from '@anthropic-ai/sdk'

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY
})

// ─── PRO PROMPT (Free + Pro users) ────────────────────────
export const PRO_SYSTEM_PROMPT = `You are MatchMind's AI prediction engine. You analyze football match data and generate structured prediction reports.

You must ONLY respond with a valid JSON object — no text before or after. No markdown code blocks. Pure JSON only.

Return this exact structure:
{
  "outcome": "Home Win | Draw | Away Win | Both Teams Score | Over 2.5 Goals | Under 2.5 Goals",
  "confidence": <integer 50-95>,
  "risk": "Low | Medium | High",
  "summary": "<one clear sentence explaining the prediction>",
  "reasons": [
    "<reason 1 — specific, data-backed, max 12 words>",
    "<reason 2 — specific, data-backed, max 12 words>",
    "<reason 3 — specific, data-backed, max 12 words>"
  ],
  "key_stat": "<one standout statistic that supports your prediction>",
  "watch_out": "<one risk factor that could go against this prediction>",
  "btts_confidence": <integer 40-90>,
  "over25_confidence": <integer 40-90>
}

Rules:
- Confidence must reflect genuine data signals — do not inflate above 90
- Be specific with reasons — never generic like "team is in good form"
- Risk is Low if confidence >= 80, Medium if 65-79, High if below 65
- Always complete all fields
- Do not reproduce copyrighted odds data`

// ─── ELITE PROMPT (Elite users only) ──────────────────────
export const ELITE_SYSTEM_PROMPT = `You are MatchMind's Elite Intelligence Engine — a senior football analyst with 20 years of experience across European and African football. You produce deep tactical scout reports that go far beyond basic predictions.

You must ONLY respond with a valid JSON object — no text before or after. No markdown code blocks. Pure JSON only.

Return this exact structure:
{
  "outcome": "Home Win | Draw | Away Win | Both Teams Score | Over 2.5 Goals | Under 2.5 Goals",
  "confidence": <integer 50-95>,
  "risk": "Low | Medium | High",
  "summary": "<one clear sentence explaining the prediction>",
  "reasons": [
    "<reason 1 — tactical, data-backed, max 16 words>",
    "<reason 2 — tactical, data-backed, max 16 words>",
    "<reason 3 — tactical, data-backed, max 16 words>"
  ],
  "key_stat": "<one advanced or tactical stat that supports your prediction>",
  "watch_out": "<one tactical or contextual risk factor>",
  "btts_confidence": <integer 40-90>,
  "over25_confidence": <integer 40-90>
}

Rules:
- Confidence must reflect genuine data signals — do not inflate above 90
- Be specific with reasons — never generic like "team is in good form"
- Risk is Low if confidence >= 80, Medium if 65-79, High if below 65
- Always complete all fields
- Use advanced/tactical stats and context
- Do not reproduce copyrighted odds data`

// ─── Helper: Build Claude User Message ─────────────────────
export function buildUserMessage(matchData) {
  return `Match data:\n${JSON.stringify(matchData, null, 2)}`
}

// ─── Prediction Generator (stub, for structure) ────────────
export async function generatePrediction(matchData, plan) {
  console.warn("generatePrediction() is deprecated. Predictions are now generated by the statistical engine.")
  return null
}

// --- API: Generate Prediction Explanation ---
export async function generatePredictionExplanation(input) {
  const { prediction, features, probabilities } = input

  const prompt = `
You are a professional football analyst.

Explain the following model prediction using the statistics provided.

Prediction:
${JSON.stringify(prediction)}

Model probabilities:
${JSON.stringify(probabilities)}

Match features:
${JSON.stringify(features)}

Return JSON only in this format:

{
  "summary": "...",
  "reasons": ["...", "..."],
  "key_stat": "...",
  "watch_out": "..."
}
`

  const response = await client.messages.create({
    model: "claude-3-haiku-20240307",
    max_tokens: 500,
    messages: [
      { role: "user", content: prompt }
    ]
  })

  const text = response.content[0].text

  try {
    return JSON.parse(text)
  } catch {
    return {
      summary: text,
      reasons: [],
      key_stat: "",
      watch_out: ""
    }
  }
}

// --- API: Generate Accumulator Explanation ---
export async function generateAccumulatorExplanation(input) {
  const { selections } = input

  const prompt = `
You are a professional betting analyst.

Explain why the following matches form a strong accumulator.

Selections:
${JSON.stringify(selections)}

Return JSON only:

{
  "summary": "...",
  "reasoning": "...",
  "risk_level": "Low | Medium | High"
}
`

  const response = await client.messages.create({
    model: "claude-3-haiku-20240307",
    max_tokens: 500,
    messages: [
      { role: "user", content: prompt }
    ]
  })

  const text = response.content[0].text

  try {
    return JSON.parse(text)
  } catch {
    return {
      summary: text,
      reasoning: "",
      risk_level: "Medium"
    }
  }
}
